### ISSUE TITLE
Enemy Wolf Animation & Implementation

### ISSUE THREAD

**Issue by benxie2016** [GoldenArmor/HostileKingdom#33]
5 animations

- [x] Attack
- [x] Walk
- [x] Run
- [x] Idle
- [x] Die

- [x] Implemented in Unity3D

**EXPECTED RESULT:**

_All animations of the Wolf In .bip to include in unity, ._

**Comment by marcvallver** [comment]
Wolf implemented in the project with its textures & animations.
