### ISSUE TITLE
Draw & desing Game Logo 

### ISSUE THREAD

**Issue by Canogar** [GoldenArmor/HostileKingdom#34]
Make a Logo of the game with Affter Efects 
References

[Tritan Studios](http://tritanstudios.com/)
[Forge of Empires](https://us.forgeofempires.com/)

**Comment by marcvallver** [comment]
New logo added to the project in [WikiResources/LogoHostileKingdom.png](https://github.com/GoldenArmor/HostileKingdom/blob/master/WikiResources/LogoHostileKingdom.png)
