### ISSUE TITLE
NPC - Mayor of the town 3D Model

### ISSUE THREAD

**Issue by benxie2016** [GoldenArmor/HostileKingdom#48]
The mayor of the town. 

* [x] **Character 3D Model**
  * [x]  High Poly
  * [x]  Low Poly
  * [x]  UVs
  * [x]  Texture

**EXPECTED RESULT:**

_He is the mayor of the town, he is an old dwarf and magician. He will give guides and missions to the player at the first level._

**Comment by marcvallver** [comment]
Model will be used in another role, waiting to be asigned.
