### ISSUE TITLE
Ally Character - Warrior 3D Animation

### ISSUE THREAD

**Issue by benxie2016** [GoldenArmor/HostileKingdom#52]
* [x] **Character Rigging**
  * [x]  Rigging
* [x] **Character Animation**
  * [x]  Idle 
  * [x]  Walk
  * [x]  Run
  * [x]  Attack
  * [x]  Passive Hability

**EXPECTED RESULT:**

_It has quite big size, the armors will be gold and silver with restricted movement. 
The movements will be a little slower_

**Comment by marcvallver** [comment]
Model generated with its animations, implemented in project.
